name: Angular CI with Bun
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Validar commits
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js [[8]]

      # Configurar Bun
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Instalar dependencias y construir
      - run: bun install
      - run: bun run lint
      - run: bun run test -- --watch=false --browsers=ChromeHeadless
      - run: bun run build -- --configuration=production